### ISSUE TITLE
【失败】支付宝Nodej创建订单报错

### ISSUE THREAD

**Issue by shawnmuggle** [alipay/alipay-sdk-nodejs-all#42]
我在开发支付接口。最近建的app 201908xxxx没有问题。但是如果是旧的app 201812xxxx就会报错。我用php代码来运行的话，新旧的app都可以创建支付宝订单。

我尝试修改其中一个参数；改为 signType: 'RSA'。但是还是旧的app依然下面的错误。不知道是否遇到类似的情况？谢谢！

{ Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
    at Sign.sign (internal/crypto/sig.js:84:29)
    at Object.sign (/xxxx-backend/node_modules/alipay-sdk/lib/util.ts:56:46)
    at AlipaySdk.exec (/xxxx-backend/node_modules/alipay-sdk/lib/alipay.ts:333:22)
    at Function.aliyunPrecreate (/xxxx-backend/src/controller/alipay.ts:181:35)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  opensslErrorStack:
   [ 'error:04093004:rsa routines:old_rsa_priv_decode:RSA lib',
     'error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error',
     'error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error' ],

**Comment by tudou527** [comment]
证书格式错误，按这份文档**逐步**操作：https://www.yuque.com/chenqiu/alipay-node-sdk/config-plantform
